#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate cited.ico + preview PNG, matched to the CITED cover on a Swiss modular grid:
bright green field (#42D949), the 'C' set in the brand font ANTON (same as the CITED
wordmark), a small white notification badge with a red '1'."""
import os, io, base64
from PIL import Image, ImageDraw, ImageFont

GREEN = (66, 217, 73, 255)     # #42D949 - CITED cover / brand green
BLACK = (10, 10, 10, 255)
RED   = (226, 59, 46, 255)
S = 256
U = S / 8                       # 32px module (8x8 grid)
HERE = os.path.dirname(os.path.abspath(__file__))
ANTON = os.path.join(HERE, "fonts", "Anton-Regular.ttf")   # brand display face

def font(sz, brand=False):
    paths = ([ANTON] if brand else []) + ["C:/Windows/Fonts/ariblk.ttf", "C:/Windows/Fonts/arialbd.ttf", "arialbd.ttf"]
    for p in paths:
        try: return ImageFont.truetype(p, int(sz))
        except Exception: pass
    return ImageFont.load_default()

def fit(dr, ch, target_h, brand=False):
    """Return a font whose glyph ink-height ~= target_h."""
    sz = 10
    while sz < 420:
        bb = dr.textbbox((0, 0), ch, font=font(sz, brand))
        if bb[3]-bb[1] >= target_h: break
        sz += 2
    return font(sz, brand)

def center(dr, ch, f, fill, cx=S/2, cy=S/2):
    bb = dr.textbbox((0, 0), ch, font=f)
    w = bb[2]-bb[0]; h = bb[3]-bb[1]
    dr.text((cx - w/2 - bb[0], cy - h/2 - bb[1]), ch, font=f, fill=fill)

def draw(img):
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([4, 4, S-4, S-4], radius=int(1.5*U), fill=GREEN)      # field
    # C in ANTON (the brand wordmark face), ink height ~= 5 modules, centred
    center(d, "C", fit(d, "C", 5.0*U, brand=True), BLACK)
    # badge: 1.5 modules, top-right, dropped onto the C's shoulder like the cover
    cs = 1.5 * U; m = 0.625 * U
    x1 = S - m - cs; y1 = 1.5 * U; r = int(cs*0.28)
    d.rounded_rectangle([x1+3, y1+4, x1+cs+3, y1+cs+4], radius=r, fill=(0, 0, 0, 45))  # shadow
    d.rounded_rectangle([x1, y1, x1+cs, y1+cs], radius=r, fill=(255, 255, 255, 255))
    center(d, "1", fit(d, "1", 0.9*U), RED, cx=x1+cs/2, cy=y1+cs/2)

base = Image.new("RGBA", (S, S), (0, 0, 0, 0)); draw(base)
base.save(os.path.join(HERE, "cited.ico"), sizes=[(16, 16), (32, 32), (48, 48), (256, 256)])
base.save(os.path.join(HERE, "cited-preview.png"))

# favicon: a 64px raster of the same Anton mark, base64'd into favicon_data.py so the
# report + app can inline it as a data-URI (raster works in browser tabs; an SVG text
# favicon could not reach the Anton web font).
fav = base.resize((64, 64), Image.LANCZOS)
buf = io.BytesIO(); fav.save(buf, "PNG")
b64 = base64.b64encode(buf.getvalue()).decode()
with open(os.path.join(HERE, "favicon_data.py"), "w") as f:
    f.write('# auto-generated by make_icon.py - 64px CITED mark (Anton C) for inline favicon\n')
    f.write('FAVICON_PNG_B64 = "%s"\n' % b64)
print("cited.ico + cited-preview.png + favicon_data.py written (C set in Anton)")
